[package]
name = "ixc"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
arrayvec = "0.7.6"
itertools = "0.14.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "lexer"
harness = false